#! /bin/sh
bspc rule -r "*"
~/.config/polybar/./launch.sh
sxhkd &
#compton --experimental-backends &
picom --experimental-backends &
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
#bspc config border_radius 10
bspc config bottom_padding 0
bspc config top_padding 56

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#CUSTOM
#feh --bg-fill $HOME/Downloads/commission-nate-w-torii-city.jpg &
feh --bg-fill $HOME/Downloads/skyblu.png &
#wal -i $HOME/Downloads/commission-nate-w-torii-city.jpg &
#wal -i $HOME/Downloads/tiger.jpg &
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1    5"
bspc config presel_feedback_color "$color    1"
bspc config focus_follows_pointer true

# Window Rules
#sleep 1
#wmctrl -r Spotify -t 9 
#exit
#bspc rule -a Spotify state=floating rectangle=500x500+500+500 sticky=off
#bspc rule -a Alacritty state=floating rectangle 600x900+200+50 sticky=off
bspc rule -a Pavucontrol state=floating rectangle 200x200+50+50 sticky=off 

# Remove x cursor
xsetroot -cursor_name left_ptr & 

#enable touchpad tapping and natural scrolling
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
